### ISSUE TITLE
About the 'PermissionError'?

### ISSUE THREAD

**Issue by fdujay** [ildoonet/pytorch-randaugment#11]
Thank you for repo! I have tried to reproduced the result, but met some problem:

> Traceback (most recent call last):
>   File "RandAugment/train.py", line 267, in <module>
>     result = train_and_eval(args.tag, args.dataroot, test_ratio=args.cv_ratio, cv_fold=args.cv, save_path=args.save, only_eval=args.only_eval, metric='test')
>   File "RandAugment/train.py", line 93, in train_and_eval
>     trainsampler, trainloader, validloader, testloader_ = get_dataloaders(C.get()['dataset'], C.get()['batch'], dataroot, test_ratio, split_idx=cv_fold)
>   File "/home/davis/anaconda3/lib/python3.7/site-packages/RandAugment/data.py", line 79, in get_dataloaders
>     total_trainset = torchvision.datasets.CIFAR10(root=dataroot, train=True, download=True, transform=transform_train)
>   File "/home/davis/anaconda3/lib/python3.7/site-packages/torchvision/datasets/cifar.py", line 64, in __init__
>     self.download()
>   File "/home/davis/anaconda3/lib/python3.7/site-packages/torchvision/datasets/cifar.py", line 148, in download
>     download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)
>   File "/home/davis/anaconda3/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 248, in download_and_extract_archive
>     download_url(url, download_root, filename, md5)
>   File "/home/davis/anaconda3/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 74, in download_url
>     makedir_exist_ok(root)
>   File "/home/davis/anaconda3/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 50, in makedir_exist_ok
>     os.makedirs(dirpath)
>   File "/home/davis/anaconda3/lib/python3.7/os.py", line 211, in makedirs
>     makedirs(head, exist_ok=exist_ok)
>   File "/home/davis/anaconda3/lib/python3.7/os.py", line 211, in makedirs
>     makedirs(head, exist_ok=exist_ok)
>   File "/home/davis/anaconda3/lib/python3.7/os.py", line 221, in makedirs
>     mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/data'
> 

If anybody know how to deal with it, please leave a commit there

**Comment by ildoonet** [comment]
You need to specify your dataset location : https://github.com/ildoonet/pytorch-randaugment/blob/master/RandAugment/train.py#L245
